# Generated by Django 4.2.7 on 2023-12-10 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_video_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranscriptDetail',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='transcripts',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transcripts',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
