# Generated by Django 4.2.7 on 2023-12-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_rename_name_transcripts_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcripts',
            old_name='file',
            new_name='file_name',
        ),
    ]
