# Generated by Django 4.2.7 on 2024-02-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0013_alter_transcripts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcripts',
            name='chatgpt_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
