# Generated by Django 4.2.7 on 2023-12-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0010_alter_transcripts_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcripts',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
