# Generated by Django 4.2.7 on 2023-11-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcripts',
            name='content',
            field=models.TextField(default='Hello there', max_length=4000),
        ),
        migrations.AlterField(
            model_name='transcripts',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
