# Generated by Django 4.2.7 on 2023-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_transcripts_content_alter_transcripts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.PositiveIntegerField(help_text='Length of the transcript in characters')),
            ],
        ),
    ]
