# Generated by Django 4.2.7 on 2023-12-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_delete_transcriptdetail_delete_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcripts',
            old_name='name',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='transcripts',
            old_name='uploaded_at',
            new_name='processed_time',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='upload_time',
        ),
    ]
