# Generated by Django 4.2.7 on 2023-12-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_rename_file_transcripts_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcripts',
            name='file_name',
            field=models.CharField(default='Hello there', max_length=255),
        ),
    ]
