# Generated by Django 4.2.7 on 2024-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_alter_transcripts_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcripts',
            name='chatgpt_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
